### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by freddi301** [KlausTrainer/dynamodbdown#2]
Hi,
It happens that you just copy-pasted your first commit from here https://github.com/davidguttman/dynamodown

And then put your name in the copyright

Feel free to close this issue when added right attribution in the readme :kissing:

**Comment by KlausTrainer** [comment]
Thanks.

My first commit was definitely not “just copy-pasted” from David Guttman's DynamoDOWN. But you're right that it's based on their work, and therefore needs attribution.

I've fixed that in 5ed1ea3. Let me know if you think there's still an issue!
